---
openapi: 3.1.0
info:
  title: Showtime API
  description: This is the API of the Showtime service
  contact:
    email: helene.coullon@imt-atlantique.fr
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
- name: users
  description: Operations available to users
paths:
  /user:
    post:
      tags:
      - users
      summary: get the reservations for a specific user ID
      operationId: book
      parameters:
        - name: user_id
          in: path
          description: ID of the user that makes the booking
          required: true
          schema:
            type: string
        - name: date
          in: path
          description: date of the booking
          required: true
          schema:
            type: string
        - name: movie_id
          in: path
          description: ID of the movie to book
          required: true
          schema:
            type: string
      responses:
        "200":
          description: the booking was made
        "404":
          description: ID does not match any user or movie or date was not found
        "409":
          description: this booking already exists
  /user/booking/movies:
    get:
      tags:
        - developers
      summary: get the bookings for a specific user ID with the films data
      operationId: get_bookings_data
      parameters:
        - name: user_id
          in: path
          description: ID of the user
          required: true
          schema:
            type: string
      responses:
        "200":
          description: the booking was made
        "400":
          description: this user does not have bookings
        "404":
          description: a film does not have data
components:
  schemas:
    AllSchedule:
      required:
      - schedule
      type: object
      properties:
        schedule:
          type: array
          items:
            $ref: '#/components/schemas/Schedule'
    Schedule:
      required:
      - date
      - movies
      type: object
      properties:
        date:
          type: string
          example: "20151130"
        movies:
          type: array
          items:
            type: string
            example: 720d006c-3a57-4b6a-b18f-9b713b073f3c
